# Generated by Django 5.2.8 on 2025-11-20 23:28

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=2256)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=9, unique=True)),
                ('avatar', models.ImageField(upload_to=users.models.user_avatar)),
            ],
        ),
    ]
