# Generated by Django 5.2.8 on 2025-12-03 22:05

import bookshelf.models.books
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('description', models.TextField()),
                ('sex', models.CharField(max_length=1)),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('size', models.DecimalField(decimal_places=0, max_digits=30)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('size', models.DecimalField(decimal_places=0, max_digits=200)),
                ('series_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField()),
                ('isbn_code', models.DecimalField(decimal_places=0, max_digits=13)),
                ('image', models.ImageField(upload_to=bookshelf.models.books.Book.book_image)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to='bookshelf.authors')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookseries')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='bookshelf.genre')),
            ],
        ),
    ]
